import Head from 'next/head'
import Image from 'next/image'
import { Product, FooterBanner, HeroBanner } from '../components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner />

        <div className='product-heading mb-6'>
            <h1 className='text-xl font-bold text-center'>Best Seller Produuct</h1>
            <p className='text-center'>Speaker there and many variant</p>
        </div>
        
        <div className='flex justify-center'>
            {['Product1', 'Product2'].map(
                (product)=>product
            )}
        </div>


      <FooterBanner />

    </div>
  )
}
